
@startwbs WBS
title ホテル予約のWBS
* ホテル予約
**[#SkyBlue] 宿泊
***[#Yellow] プランを決める
****[#Yellow] プランの検索機能
***[#Yellow] カレンダーで日付選択
***[#Yellow] 空き室確認
***[#Yellow] 料金表示(プランや部屋の)
****[#Yellow] 平日、休日で違う料金設定
***[#Yellow] オプション選択(最大8個)
***[#Yellow] 個人情報入力
***[#Yellow] 割引などの選択
***[#Yellow] 料金の計算
***[#Yellow] 確認のメール送信
**[#SkyBlue] 宴会
***[#Yellow] プランを決める
****[#Yellow] プランの検索機能
***[#Yellow] カレンダーで日付選択
***[#Yellow] 空き室確認
***[#Yellow] 料金表示(プランや部屋の)
****[#Yellow] 平日、休日で違う料金設定
***[#Yellow] オプション選択
****[#Yellow] 宴会プランでの飲み放題コースの事前付与
***[#Yellow] 個人情報入力
***[#Yellow] 割引などの選択
***[#Yellow] 宴会プランにおいて子供料金を適用外にする条件
***[#Yellow] 料金の計算
***[#Yellow] 確認のメール送信
@endwbs