@startuml ホテル予約システム
title ホテル予約システム

start 

:宿泊か宴会を決める;
fork
:宿泊;
:プランを決める;
:プランの検索機能;
:カレンダーで日付選択;
:空き室確認;
:料金表示;
:平日や休日で違う料金設定;
:オプション設定;
:料金の計算;
fork again
:宴会;
:プランを決める;
:プランの検索機能;
:カレンダーで日付選択;
:空き室確認;
:料金表示;
:平日や休日で違う料金設定;
:オプション設定;
:宴会プランにおいて子供料金を適用外にする条件;
:料金の計算;
end fork
:確認のメール送信;

